import SELECTED_MOVIES from "./movies";
import  SELECTED_MOVIES_SAME_RATING from "./same-rating-movies";

const AVENGERS_CODE = "tt4154756";
const INCREDIBLES_CODE = "tt3606756";
const DEADPOOL_CODE = "tt5463162";

export{
    SELECTED_MOVIES_SAME_RATING,
    SELECTED_MOVIES,
    AVENGERS_CODE,
    INCREDIBLES_CODE,
    DEADPOOL_CODE,
}